### ISSUE TITLE
textLine displays two times text input at Banner

### ISSUE THREAD

**Issue by antekai** [essserrr/crt-terminal#3]
textLine displays two times text input at Banner

Codesandbox example:
https://codesandbox.io/s/duplicated-banner-lkylcl?file=/src/App.j

![Screenshot 2022-05-01 at 12 30 46](https://user-images.githubusercontent.com/8102932/166142077-8bcd3324-100e-4974-87e4-3c9216e6ebcb.png)
s

**Comment by antekai** [comment]
A workaround for this issue is to add one extra item at `textLine.words` array
For example adding a random string as it follows
```jsx
<Terminal
     banner={[
          textLine({
            words: [textWord({ characters: bannerText }), "block-bannerText-duplication"],
          }),
        ]}
  ...............
  ...............
/>
```

**Comment by essserrr** [comment]
Thanks for reporting. 
React hook onMount event (useEffect(() => {}, []);) triggers twice in strict mode.
[Question on Stack overflow with similar problem](https://stackoverflow.com/questions/61254372/my-react-component-is-rendering-twice-because-of-strict-mode) and [official docs reference (you are looking for double-invoking)](https://reactjs.org/docs/strict-mode.html#detecting-unexpected-side-effects).

The terminal prints banner with simple print() request on component mount, so you see two banners in your example. If you still consider it as a bug, let me know, it can be easily fixed.

**Comment by null-prophet** [comment]
how can you fix this issue? would be nice to have working in nextjs latest versions

**Comment by mrv777** [comment]
@null-prophet In you next.config make sure it says:
```
const nextConfig = {
  reactStrictMode: false,
  ...
};

**Comment by essserrr** [comment]
In the end I decided to fix it, since so many users find this feature so confusing
